-- 当前完整表结构参考 SQL。
-- 说明：
-- 1. 本文件用于文档、审阅和新环境核对，实际迁移仍以 backend/alembic/versions 为准。
-- 2. 建库请先执行 resources/sql/00_create_database.sql。
-- 3. 视图请执行 resources/sql/01_readonly_views.sql。

USE stock_ah_ai;

CREATE TABLE IF NOT EXISTS `a_stock_basic` (
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码，主键，例如 600000.SH',
  `symbol` VARCHAR(16) DEFAULT NULL COMMENT '股票交易代码，不含交易所后缀',
  `name` VARCHAR(64) NOT NULL COMMENT '股票简称',
  `area` VARCHAR(64) DEFAULT NULL COMMENT '所属地域',
  `industry` VARCHAR(128) DEFAULT NULL COMMENT '所属行业',
  `fullname` VARCHAR(255) DEFAULT NULL COMMENT '股票全称',
  `market` VARCHAR(64) DEFAULT NULL COMMENT '市场类型，例如主板、创业板、科创板',
  `exchange` VARCHAR(16) DEFAULT NULL COMMENT '交易所代码，例如 SSE、SZSE',
  `curr_type` VARCHAR(16) DEFAULT NULL COMMENT '交易币种',
  `list_status` VARCHAR(8) DEFAULT NULL COMMENT '上市状态，L 表示上市',
  `list_date` DATE DEFAULT NULL COMMENT '上市日期',
  `delist_date` DATE DEFAULT NULL COMMENT '退市日期',
  `is_hs` VARCHAR(8) DEFAULT NULL COMMENT '是否沪深港通标的',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股基础信息表';

CREATE TABLE IF NOT EXISTS `hk_stock_basic` (
  `ts_code` VARCHAR(16) NOT NULL COMMENT '港股 Tushare 代码，主键，例如 00700.HK',
  `name` VARCHAR(128) NOT NULL COMMENT '港股中文简称',
  `fullname` VARCHAR(255) DEFAULT NULL COMMENT '港股中文全称',
  `enname` VARCHAR(255) DEFAULT NULL COMMENT '港股英文名称',
  `cn_spell` VARCHAR(64) DEFAULT NULL COMMENT '中文拼音缩写',
  `market` VARCHAR(64) DEFAULT NULL COMMENT '市场类型',
  `list_status` VARCHAR(8) DEFAULT NULL COMMENT '上市状态，L 表示上市',
  `list_date` DATE DEFAULT NULL COMMENT '上市日期',
  `delist_date` DATE DEFAULT NULL COMMENT '退市日期',
  `trade_unit` DECIMAL(18,4) DEFAULT NULL COMMENT '每手股数',
  `isin` VARCHAR(32) DEFAULT NULL COMMENT 'ISIN 代码',
  `curr_type` VARCHAR(16) DEFAULT NULL COMMENT '交易币种',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='港股基础信息表';

CREATE TABLE IF NOT EXISTS `a_trade_calendar` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `exchange` VARCHAR(16) NOT NULL COMMENT '交易所代码，默认 SSE',
  `cal_date` DATE NOT NULL COMMENT '日历日期',
  `is_open` INT NOT NULL COMMENT '是否开市，1 开市，0 休市',
  `pretrade_date` DATE DEFAULT NULL COMMENT '上一交易日',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_trade_calendar` (`exchange`, `cal_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股交易日历表';

CREATE TABLE IF NOT EXISTS `hk_trade_calendar` (
  `cal_date` DATE NOT NULL COMMENT '港股日历日期，主键',
  `is_open` INT NOT NULL COMMENT '是否开市，1 开市，0 休市',
  `pretrade_date` DATE DEFAULT NULL COMMENT '上一交易日',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`cal_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='港股交易日历表';

CREATE TABLE IF NOT EXISTS `a_daily_quote` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `trade_date` DATE NOT NULL COMMENT '交易日期',
  `open` DECIMAL(20,6) DEFAULT NULL COMMENT '开盘价',
  `high` DECIMAL(20,6) DEFAULT NULL COMMENT '最高价',
  `low` DECIMAL(20,6) DEFAULT NULL COMMENT '最低价',
  `close` DECIMAL(20,6) DEFAULT NULL COMMENT '收盘价',
  `pre_close` DECIMAL(20,6) DEFAULT NULL COMMENT '昨收价',
  `change_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '涨跌额',
  `pct_chg` DECIMAL(12,6) DEFAULT NULL COMMENT '涨跌幅，单位百分比',
  `vol` DECIMAL(24,6) DEFAULT NULL COMMENT '成交量',
  `amount` DECIMAL(24,6) DEFAULT NULL COMMENT '成交额',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_daily_quote` (`ts_code`, `trade_date`),
  KEY `idx_a_daily_trade_date` (`trade_date`),
  KEY `idx_a_daily_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股日线行情表';

CREATE TABLE IF NOT EXISTS `a_daily_basic` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `trade_date` DATE NOT NULL COMMENT '交易日期',
  `close` DECIMAL(20,6) DEFAULT NULL COMMENT '收盘价',
  `turnover_rate` DECIMAL(20,8) DEFAULT NULL COMMENT '换手率',
  `volume_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '量比',
  `pe` DECIMAL(20,8) DEFAULT NULL COMMENT '市盈率',
  `pe_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT '滚动市盈率',
  `pb` DECIMAL(20,8) DEFAULT NULL COMMENT '市净率',
  `ps` DECIMAL(20,8) DEFAULT NULL COMMENT '市销率',
  `ps_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT '滚动市销率',
  `dv_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '股息率',
  `dv_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT '滚动股息率',
  `total_share` DECIMAL(24,6) DEFAULT NULL COMMENT '总股本',
  `float_share` DECIMAL(24,6) DEFAULT NULL COMMENT '流通股本',
  `free_share` DECIMAL(24,6) DEFAULT NULL COMMENT '自由流通股本',
  `total_mv` DECIMAL(24,6) DEFAULT NULL COMMENT '总市值',
  `circ_mv` DECIMAL(24,6) DEFAULT NULL COMMENT '流通市值',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON，便于审计字段缺口',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_daily_basic` (`ts_code`, `trade_date`),
  KEY `idx_a_daily_basic_date` (`trade_date`),
  KEY `idx_a_daily_basic_code_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股每日估值指标表';

CREATE TABLE IF NOT EXISTS `hk_daily_quote` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT '港股 Tushare 代码',
  `trade_date` DATE NOT NULL COMMENT '交易日期',
  `open` DECIMAL(20,6) DEFAULT NULL COMMENT '开盘价',
  `high` DECIMAL(20,6) DEFAULT NULL COMMENT '最高价',
  `low` DECIMAL(20,6) DEFAULT NULL COMMENT '最低价',
  `close` DECIMAL(20,6) DEFAULT NULL COMMENT '收盘价',
  `pre_close` DECIMAL(20,6) DEFAULT NULL COMMENT '昨收价',
  `change_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '涨跌额',
  `pct_chg` DECIMAL(12,6) DEFAULT NULL COMMENT '涨跌幅，单位百分比',
  `vol` DECIMAL(24,6) DEFAULT NULL COMMENT '成交量',
  `amount` DECIMAL(24,6) DEFAULT NULL COMMENT '成交额',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hk_daily_quote` (`ts_code`, `trade_date`),
  KEY `idx_hk_daily_trade_date` (`trade_date`),
  KEY `idx_hk_daily_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='港股日线行情表，当前 token 无权限时仅保留结构';

CREATE TABLE IF NOT EXISTS `hsgt_constituent` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT '标的股票代码',
  `trade_date` DATE NOT NULL COMMENT '名单生效交易日',
  `connect_type` VARCHAR(16) NOT NULL COMMENT '沪深港通类型，例如 SH_HK、SZ_HK、HK_SH、HK_SZ',
  `name` VARCHAR(128) DEFAULT NULL COMMENT '股票名称',
  `type_name` VARCHAR(128) DEFAULT NULL COMMENT '类型名称',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hsgt_constituent` (`trade_date`, `ts_code`, `connect_type`),
  KEY `idx_hsgt_date_type` (`trade_date`, `connect_type`),
  KEY `idx_hsgt_ts_code` (`ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='沪深港通标的名单表';

CREATE TABLE IF NOT EXISTS `fx_rate_daily` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `rate_pair` VARCHAR(32) NOT NULL COMMENT '标准化汇率对，例如 HKD_CNY、USD_HKD',
  `rate_date` DATE NOT NULL COMMENT '汇率日期',
  `base_ccy` VARCHAR(8) NOT NULL COMMENT '基础货币',
  `quote_ccy` VARCHAR(8) NOT NULL COMMENT '计价货币',
  `mid_rate` DECIMAL(20,8) DEFAULT NULL COMMENT '中间价或计算用汇率',
  `bid_close` DECIMAL(20,8) DEFAULT NULL COMMENT '收盘买价',
  `ask_close` DECIMAL(20,8) DEFAULT NULL COMMENT '收盘卖价',
  `source` VARCHAR(32) NOT NULL COMMENT '汇率来源，例如 TUSHARE_FXCM、MANUAL',
  `raw_ts_code` VARCHAR(32) DEFAULT NULL COMMENT '原始 Tushare 汇率代码',
  `is_cross_rate` TINYINT(1) NOT NULL COMMENT '是否为交叉汇率计算结果',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fx_rate_daily` (`rate_pair`, `rate_date`, `source`),
  KEY `idx_fx_pair_date` (`rate_pair`, `rate_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='外汇汇率日线表';

CREATE TABLE IF NOT EXISTS `tencent_unadjusted_daily_quote` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `market` VARCHAR(8) NOT NULL COMMENT '市场: A、HK',
  `ts_code` VARCHAR(16) NOT NULL COMMENT '项目标准代码，如 600036.SH、03968.HK',
  `tencent_symbol` VARCHAR(32) NOT NULL COMMENT '腾讯 symbol，如 sh600036、hk03968',
  `trade_date` DATE NOT NULL COMMENT '交易日期',
  `open` DECIMAL(20,6) DEFAULT NULL COMMENT '不复权开盘价',
  `close` DECIMAL(20,6) NOT NULL COMMENT '不复权收盘价',
  `high` DECIMAL(20,6) DEFAULT NULL COMMENT '不复权最高价',
  `low` DECIMAL(20,6) DEFAULT NULL COMMENT '不复权最低价',
  `volume` DECIMAL(24,4) DEFAULT NULL COMMENT '成交量，按腾讯原始单位保存',
  `amount` DECIMAL(24,4) DEFAULT NULL COMMENT '成交额，按腾讯原始单位保存',
  `amplitude` DECIMAL(20,6) DEFAULT NULL COMMENT '振幅',
  `pct_chg` DECIMAL(20,6) DEFAULT NULL COMMENT '涨跌幅',
  `change_amount` DECIMAL(20,6) DEFAULT NULL COMMENT '涨跌额',
  `turnover_rate` DECIMAL(20,6) DEFAULT NULL COMMENT '换手率',
  `adjust_type` VARCHAR(16) NOT NULL DEFAULT 'NONE' COMMENT '复权类型: NONE 不复权',
  `data_source` VARCHAR(32) NOT NULL DEFAULT 'TENCENT_KLINE' COMMENT '数据来源',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT '原始单行数据或摘要 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tencent_unadj_quote` (`market`, `ts_code`, `trade_date`, `adjust_type`),
  KEY `idx_tencent_unadj_quote_date` (`trade_date`),
  KEY `idx_tencent_unadj_quote_code_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='腾讯不复权历史日线表';

CREATE TABLE IF NOT EXISTS `waterstock_fx_rate_daily` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `currency_pair` VARCHAR(16) NOT NULL COMMENT '汇率对，如 HKDCNY',
  `rate_date` DATE NOT NULL COMMENT '汇率日期',
  `open` DECIMAL(20,8) DEFAULT NULL COMMENT '开盘汇率',
  `close` DECIMAL(20,8) NOT NULL COMMENT '收盘汇率',
  `high` DECIMAL(20,8) DEFAULT NULL COMMENT '最高汇率',
  `low` DECIMAL(20,8) DEFAULT NULL COMMENT '最低汇率',
  `data_source` VARCHAR(32) NOT NULL DEFAULT 'WATER_STOCK_BAIDU_FX' COMMENT '汇率来源',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT '原始响应摘要 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_waterstock_fx_rate` (`currency_pair`, `rate_date`, `data_source`),
  KEY `idx_waterstock_fx_rate_date` (`rate_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='water-stock 历史汇率日线表';

CREATE TABLE IF NOT EXISTS `ah_stock_pair` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `a_ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `hk_ts_code` VARCHAR(16) NOT NULL COMMENT 'H 股 Tushare 代码',
  `a_name` VARCHAR(128) DEFAULT NULL COMMENT 'A 股名称',
  `hk_name` VARCHAR(128) DEFAULT NULL COMMENT 'H 股名称',
  `source` VARCHAR(32) NOT NULL COMMENT '配对来源，例如 TUSHARE_STK_AH、MANUAL',
  `effective_start_date` DATE DEFAULT NULL COMMENT '配对生效开始日期',
  `effective_end_date` DATE DEFAULT NULL COMMENT '配对生效结束日期',
  `is_active` TINYINT(1) NOT NULL COMMENT '是否启用该配对',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ah_stock_pair` (`a_ts_code`, `hk_ts_code`),
  KEY `idx_ah_pair_hk` (`hk_ts_code`),
  KEY `idx_ah_pair_a` (`a_ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AH 股票配对表';

CREATE TABLE IF NOT EXISTS `official_ah_comparison` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `trade_date` DATE NOT NULL COMMENT '交易日期',
  `a_ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `hk_ts_code` VARCHAR(16) NOT NULL COMMENT 'H 股 Tushare 代码',
  `a_name` VARCHAR(128) DEFAULT NULL COMMENT 'A 股名称',
  `hk_name` VARCHAR(128) DEFAULT NULL COMMENT 'H 股名称',
  `a_close` DECIMAL(20,6) DEFAULT NULL COMMENT 'A 股收盘价，人民币',
  `a_pct_chg` DECIMAL(12,6) DEFAULT NULL COMMENT 'A 股涨跌幅，单位百分比',
  `hk_close` DECIMAL(20,6) DEFAULT NULL COMMENT 'H 股收盘价，港币',
  `hk_pct_chg` DECIMAL(12,6) DEFAULT NULL COMMENT 'H 股涨跌幅，单位百分比',
  `ah_comparison` DECIMAL(20,8) DEFAULT NULL COMMENT '官方 A/H 比价',
  `ah_premium` DECIMAL(20,8) DEFAULT NULL COMMENT '官方 A/H 溢价，单位百分比',
  `ha_comparison` DECIMAL(20,8) DEFAULT NULL COMMENT 'H/A 比价，由 A/H 比价反推',
  `ha_premium` DECIMAL(20,8) DEFAULT NULL COMMENT 'H/A 溢价，单位百分比，由 H/A 比价计算',
  `is_realtime` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否实时或手工重算来源',
  `data_source` VARCHAR(32) NOT NULL DEFAULT 'TUSHARE_OFFICIAL' COMMENT '数据来源标记',
  `source_updated_at` DATETIME DEFAULT NULL COMMENT '来源更新时间或派生指标重算时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_official_ah` (`trade_date`, `a_ts_code`, `hk_ts_code`),
  KEY `idx_official_ah_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tushare 官方 AH 比价快照表，当前主展示口径';

CREATE TABLE IF NOT EXISTS `historical_premium_backfill_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `a_ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `hk_ts_code` VARCHAR(16) NOT NULL COMMENT 'H 股 Tushare 代码',
  `data_source` VARCHAR(32) NOT NULL COMMENT '补数来源标记',
  `status` VARCHAR(16) NOT NULL COMMENT '补数状态: RUNNING、COMPLETED、FAILED',
  `candidate_rows` INT NOT NULL DEFAULT 0 COMMENT '三方数据交集候选行数',
  `inserted_rows` INT NOT NULL DEFAULT 0 COMMENT '实际新增行数',
  `skipped_existing_rows` INT NOT NULL DEFAULT 0 COMMENT '唯一键已存在跳过行数',
  `skipped_invalid_rows` INT NOT NULL DEFAULT 0 COMMENT '价格或汇率无效跳过行数',
  `first_trade_date` DATE DEFAULT NULL COMMENT '本轮候选最早交易日期',
  `last_trade_date` DATE DEFAULT NULL COMMENT '本轮候选最晚交易日期',
  `last_error` VARCHAR(512) DEFAULT NULL COMMENT '失败原因摘要',
  `started_at` DATETIME DEFAULT NULL COMMENT '最近一次开始时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '最近一次成功完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hist_premium_backfill_pair` (`a_ts_code`, `hk_ts_code`, `data_source`),
  KEY `idx_hist_premium_backfill_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Baidu 历史 AH 比价补数执行记录表';

CREATE TABLE IF NOT EXISTS `historical_ah_unadjusted_backfill_run` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `a_ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `hk_ts_code` VARCHAR(16) NOT NULL COMMENT 'H 股 Tushare 代码',
  `data_source` VARCHAR(32) NOT NULL COMMENT '补数来源标记',
  `status` VARCHAR(16) NOT NULL COMMENT '状态: RUNNING、COMPLETED、FAILED',
  `candidate_rows` INT NOT NULL DEFAULT 0 COMMENT 'A/H/汇率三方日期交集行数',
  `inserted_rows` INT NOT NULL DEFAULT 0 COMMENT '写入官方 AH 主表行数',
  `skipped_existing_rows` INT NOT NULL DEFAULT 0 COMMENT '主表唯一键已存在跳过行数',
  `skipped_invalid_rows` INT NOT NULL DEFAULT 0 COMMENT '价格或汇率无效跳过行数',
  `first_trade_date` DATE DEFAULT NULL COMMENT '本轮最早日期',
  `last_trade_date` DATE DEFAULT NULL COMMENT '本轮最晚日期',
  `last_error` VARCHAR(512) DEFAULT NULL COMMENT '失败原因摘要',
  `started_at` DATETIME DEFAULT NULL COMMENT '最近开始时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '最近完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_unadj_backfill_pair` (`a_ts_code`, `hk_ts_code`, `data_source`),
  KEY `idx_unadj_backfill_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='不复权历史 AH 比价补数执行记录表';

CREATE TABLE IF NOT EXISTS `realtime_quote_snapshot` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `market` VARCHAR(8) NOT NULL COMMENT '报价市场：A、HK、FX',
  `symbol` VARCHAR(32) NOT NULL COMMENT '标准代码，如 600036.SH、03968.HK、HKD/CNY',
  `last_price` DECIMAL(20,8) DEFAULT NULL COMMENT '最新价或汇率',
  `currency` VARCHAR(8) NOT NULL COMMENT '价格币种，如 CNY、HKD',
  `quote_time` DATETIME DEFAULT NULL COMMENT '行情源报价时间',
  `source` VARCHAR(64) NOT NULL COMMENT '行情来源，如 MANUAL、QOS、FUTU_OPENAPI、FXAPI',
  `quality` VARCHAR(32) NOT NULL DEFAULT 'UNAVAILABLE' COMMENT '报价质量：REALTIME、DELAYED、STALE、ERROR、UNAVAILABLE',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT '原始响应摘要 JSON，不存敏感字段',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否作为有效快照参与读取',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_realtime_quote_symbol_time` (`market`, `symbol`, `quote_time`),
  KEY `idx_realtime_quote_source_time` (`source`, `quote_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实时行情快照表';

CREATE TABLE IF NOT EXISTS `app_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `username` VARCHAR(64) NOT NULL COMMENT '登录用户名',
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'PBKDF2 密码哈希',
  `role` VARCHAR(32) NOT NULL DEFAULT 'USER' COMMENT '用户角色，ADMIN 或 USER',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `display_name` VARCHAR(64) DEFAULT NULL COMMENT '展示名称',
  `email` VARCHAR(128) DEFAULT NULL COMMENT '邮箱',
  `phone` VARCHAR(32) DEFAULT NULL COMMENT '电话',
  `bio` TEXT DEFAULT NULL COMMENT '个人简介或备注',
  `menu_permissions_json` TEXT DEFAULT NULL COMMENT '用户粒度菜单权限 JSON',
  `overview_chart_settings_json` TEXT DEFAULT NULL COMMENT '总览趋势图用户粒度指标显示配置 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='应用用户表';

CREATE TABLE IF NOT EXISTS `invitation_code` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `code` VARCHAR(64) NOT NULL COMMENT '邀请码',
  `created_by_user_id` INT DEFAULT NULL COMMENT '创建管理员用户 ID',
  `used_by_user_id` INT DEFAULT NULL COMMENT '使用该邀请码注册的用户 ID',
  `used_at` DATETIME DEFAULT NULL COMMENT '使用时间',
  `note` TEXT DEFAULT NULL COMMENT '备注',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_invitation_code` (`code`),
  KEY `idx_invitation_created_by` (`created_by_user_id`),
  KEY `idx_invitation_used_by` (`used_by_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='注册邀请码表';

CREATE TABLE IF NOT EXISTS `ai_image_generation` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL COMMENT '创建图片的系统用户 ID，普通用户查询按此字段隔离',
  `prompt` TEXT NOT NULL COMMENT '用户提交的原始图片提示词',
  `model` VARCHAR(64) NOT NULL COMMENT '实际调用的文生图模型',
  `size` VARCHAR(32) NOT NULL COMMENT '实际请求的图片尺寸',
  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '生成状态，GENERATING、READY、FAILED',
  `provider` VARCHAR(64) NOT NULL DEFAULT '86gamestore' COMMENT '图片生成供应商标识',
  `generation_mode` VARCHAR(32) NOT NULL DEFAULT 'TEXT_TO_IMAGE' COMMENT '生成模式，TEXT_TO_IMAGE 或 IMAGE_REFERENCE',
  `mime_type` VARCHAR(64) DEFAULT NULL COMMENT '输出图片 MIME 类型',
  `file_relative_path` VARCHAR(512) DEFAULT NULL COMMENT '输出图片相对独立数据盘存储路径',
  `file_size_bytes` INT DEFAULT NULL COMMENT '输出图片字节数',
  `file_sha256` VARCHAR(64) DEFAULT NULL COMMENT '输出图片 SHA256',
  `reference_file_relative_path` VARCHAR(512) DEFAULT NULL COMMENT '参考图相对独立数据盘存储路径',
  `reference_mime_type` VARCHAR(64) DEFAULT NULL COMMENT '参考图 MIME 类型',
  `reference_file_size_bytes` INT DEFAULT NULL COMMENT '参考图字节数',
  `reference_file_sha256` VARCHAR(64) DEFAULT NULL COMMENT '参考图 SHA256',
  `external_url_expires_unknown` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '供应商返回的外部 URL 是否可能过期',
  `request_payload_json` LONGTEXT DEFAULT NULL COMMENT '脱敏后的供应商请求摘要，不含鉴权头和 API Key',
  `response_summary_json` LONGTEXT DEFAULT NULL COMMENT '脱敏后的供应商响应摘要',
  `elapsed_ms` DOUBLE DEFAULT NULL COMMENT '生成、下载和落盘总耗时毫秒',
  `error_message` VARCHAR(512) DEFAULT NULL COMMENT '失败摘要，不包含密钥',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '逻辑删除时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_ai_image_generation_user_created` (`user_id`, `created_at`),
  KEY `idx_ai_image_generation_status_created` (`status`, `created_at`),
  KEY `idx_ai_image_generation_file_sha` (`file_sha256`),
  KEY `idx_ai_image_generation_reference_sha` (`reference_file_sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 图片生成记录表';

CREATE TABLE IF NOT EXISTS `ai_image_user_quota` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL COMMENT '系统用户 ID',
  `daily_limit` INT NOT NULL DEFAULT 10 COMMENT '每日可生成次数，0 表示不可生成',
  `quota_date` DATE DEFAULT NULL COMMENT '当前计数日期，按东八区计算',
  `used_count` INT NOT NULL DEFAULT 0 COMMENT '当日已使用次数，调用失败会返还',
  `last_reset_at` DATETIME DEFAULT NULL COMMENT '管理员最近重置时间',
  `updated_by_user_id` INT DEFAULT NULL COMMENT '最近维护管理员用户 ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_image_user_quota_user` (`user_id`),
  KEY `idx_ai_image_user_quota_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI 图片生成用户每日次数配置表';

CREATE TABLE IF NOT EXISTS `watchlist_stock` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL DEFAULT 1 COMMENT '所属用户 ID',
  `target_type` VARCHAR(16) NOT NULL DEFAULT 'PAIR' COMMENT '关注标的类型，PAIR 为 A/H 配对，A_ONLY 为单 A 股，H_ONLY 为单 H 股',
  `target_key` VARCHAR(40) NOT NULL COMMENT '关注标的统一唯一键，PAIR 使用 A|H，单侧关注使用对应 Tushare 代码',
  `a_ts_code` VARCHAR(16) DEFAULT NULL COMMENT 'A 股 Tushare 代码，单 H 股关注时为空',
  `hk_ts_code` VARCHAR(16) DEFAULT NULL COMMENT 'H 股 Tushare 代码，单 A 股关注时为空',
  `display_name` VARCHAR(128) DEFAULT NULL COMMENT '用户自定义展示名',
  `preferred_direction` VARCHAR(8) NOT NULL DEFAULT 'HA' COMMENT '关注方向，AH 或 HA',
  `target_premium_pct` DECIMAL(20,8) DEFAULT NULL COMMENT '目标溢价或折价阈值，单位百分比',
  `push_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用消息推送，默认开启',
  `a_price_alert_enabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用 A 股股价提醒',
  `a_price_alert_operator` VARCHAR(8) NOT NULL DEFAULT 'GTE' COMMENT 'A 股股价提醒触发方向，GTE 大于等于，LTE 小于等于',
  `a_price_alert_target_price` DECIMAL(20,6) DEFAULT NULL COMMENT 'A 股股价提醒目标价格，人民币',
  `h_price_alert_enabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用 H 股股价提醒',
  `h_price_alert_operator` VARCHAR(8) NOT NULL DEFAULT 'GTE' COMMENT 'H 股股价提醒触发方向，GTE 大于等于，LTE 小于等于',
  `h_price_alert_target_price` DECIMAL(20,6) DEFAULT NULL COMMENT 'H 股股价提醒目标价格，港币',
  `holding_market` VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN' COMMENT '当前持有侧，A、H 或 UNKNOWN',
  `sort_order` INT NOT NULL DEFAULT 1000 COMMENT '自选展示排序',
  `note` TEXT DEFAULT NULL COMMENT '用户备注',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用该自选股',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_watchlist_user_target` (`user_id`, `target_type`, `target_key`),
  KEY `idx_watchlist_active_order` (`is_active`, `sort_order`),
  KEY `idx_watchlist_a_code` (`a_ts_code`),
  KEY `idx_watchlist_hk_code` (`hk_ts_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户关注标的表，支持 A/H 配对机会和单市场股价提醒';

CREATE TABLE IF NOT EXISTS `pushplus_binding` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL COMMENT '所属用户 ID',
  `friend_id` INT NOT NULL COMMENT 'PushPlus 好友 ID',
  `friend_token` VARCHAR(128) NOT NULL COMMENT 'PushPlus 好友令牌，仅后端发送使用',
  `friend_nick_name` VARCHAR(128) DEFAULT NULL COMMENT 'PushPlus 好友昵称',
  `friend_remark` VARCHAR(128) DEFAULT NULL COMMENT 'PushPlus 好友备注',
  `is_follow` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否关注 PushPlus 微信公众号',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '绑定是否启用',
  `bound_at` DATETIME NOT NULL COMMENT '绑定时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pushplus_binding_user` (`user_id`),
  KEY `idx_pushplus_binding_active` (`is_active`),
  CONSTRAINT `fk_pushplus_binding_user`
    FOREIGN KEY (`user_id`) REFERENCES `app_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='PushPlus 好友绑定表';

CREATE TABLE IF NOT EXISTS `alert_event` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL COMMENT '所属用户 ID',
  `watchlist_id` INT DEFAULT NULL COMMENT '触发提醒的自选股 ID',
  `event_type` VARCHAR(32) NOT NULL COMMENT '提醒类型，如 THRESHOLD_REACHED、PRICE_REACHED',
  `trading_day` DATE NOT NULL COMMENT '提醒所属交易日',
  `metric_direction` VARCHAR(8) DEFAULT NULL COMMENT '溢价提醒方向，AH 或 HA',
  `metric_premium_pct` DECIMAL(20,8) DEFAULT NULL COMMENT '触发时溢价指标',
  `target_premium_pct` DECIMAL(20,8) DEFAULT NULL COMMENT '用户设置的溢价目标阈值',
  `price_alert_market` VARCHAR(8) DEFAULT NULL COMMENT '股价提醒市场，A 或 H',
  `price_alert_operator` VARCHAR(8) DEFAULT NULL COMMENT '股价提醒触发方向，GTE 或 LTE',
  `price_alert_ts_code` VARCHAR(16) DEFAULT NULL COMMENT '股价提醒证券代码',
  `last_price` DECIMAL(20,6) DEFAULT NULL COMMENT '触发时价格',
  `target_price` DECIMAL(20,6) DEFAULT NULL COMMENT '用户设置的目标价格',
  `message_title` VARCHAR(128) NOT NULL COMMENT '推送标题',
  `message_content` TEXT NOT NULL COMMENT '推送内容',
  `push_channel` VARCHAR(32) NOT NULL DEFAULT 'PUSHPLUS' COMMENT '推送渠道',
  `push_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '推送状态',
  `push_message_id` VARCHAR(128) DEFAULT NULL COMMENT 'PushPlus 消息流水号',
  `error_message` TEXT DEFAULT NULL COMMENT '失败错误信息',
  `dedupe_key` VARCHAR(255) NOT NULL COMMENT '同一交易日提醒去重键',
  `sent_at` DATETIME DEFAULT NULL COMMENT '发送时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_alert_event_dedupe` (`dedupe_key`),
  KEY `idx_alert_event_user_day` (`user_id`, `trading_day`),
  KEY `idx_alert_event_watchlist` (`watchlist_id`),
  CONSTRAINT `fk_alert_event_user`
    FOREIGN KEY (`user_id`) REFERENCES `app_user` (`id`),
  CONSTRAINT `fk_alert_event_watchlist`
    FOREIGN KEY (`watchlist_id`) REFERENCES `watchlist_stock` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='提醒事件与推送记录表';

CREATE TABLE IF NOT EXISTS `pushplus_message_log` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL COMMENT '接收系统用户 ID',
  `alert_event_id` INT DEFAULT NULL COMMENT '关联提醒事件 ID，测试推送为空',
  `recipient_type` VARCHAR(16) NOT NULL COMMENT '接收类型，FRIEND 好友消息或 PERSONAL 一对一消息',
  `recipient_friend_id` INT DEFAULT NULL COMMENT 'PushPlus 好友 ID，一对一消息为空',
  `recipient_name` VARCHAR(128) DEFAULT NULL COMMENT '接收对象展示名称',
  `message_title` VARCHAR(128) NOT NULL COMMENT '推送标题',
  `message_content` TEXT NOT NULL COMMENT '推送内容',
  `push_channel` VARCHAR(32) NOT NULL DEFAULT 'PUSHPLUS' COMMENT '推送渠道',
  `push_status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '推送状态',
  `push_message_id` VARCHAR(128) DEFAULT NULL COMMENT 'PushPlus 消息流水号',
  `error_message` TEXT DEFAULT NULL COMMENT '失败错误信息',
  `sent_at` DATETIME DEFAULT NULL COMMENT '发送成功时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_pushplus_message_log_user_created` (`user_id`, `created_at`),
  KEY `idx_pushplus_message_log_status_created` (`push_status`, `created_at`),
  CONSTRAINT `fk_pushplus_message_log_user`
    FOREIGN KEY (`user_id`) REFERENCES `app_user` (`id`),
  CONSTRAINT `fk_pushplus_message_log_alert_event`
    FOREIGN KEY (`alert_event_id`) REFERENCES `alert_event` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='PushPlus 推送消息流水表';

CREATE TABLE IF NOT EXISTS `limit_up_analysis_cache` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `trade_date` DATE NOT NULL COMMENT '打板报告对应 A 股交易日',
  `model` VARCHAR(64) NOT NULL COMMENT '生成报告使用的 LLM 模型',
  `prompt_version` VARCHAR(64) NOT NULL COMMENT '提示词版本，用于区分报告生成口径',
  `data_snapshot_hash` VARCHAR(64) NOT NULL COMMENT '结构化上下文快照哈希，用于重跑幂等',
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '报告状态，PENDING、GENERATING、READY、FAILED',
  `title` VARCHAR(160) NOT NULL COMMENT '报告标题',
  `content_html` LONGTEXT DEFAULT NULL COMMENT '适合 PushPlus 和公开页展示的完整 HTML 报告',
  `content_markdown` LONGTEXT DEFAULT NULL COMMENT 'LLM 原始或规范化 Markdown 内容',
  `context_json` LONGTEXT DEFAULT NULL COMMENT '送入模型的结构化上下文 JSON',
  `data_quality_json` LONGTEXT DEFAULT NULL COMMENT '各数据接口成功、缺失或失败的质量记录 JSON',
  `error_message` TEXT DEFAULT NULL COMMENT '报告生成失败摘要',
  `generated_at` DATETIME DEFAULT NULL COMMENT '报告生成完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_limit_up_analysis_snapshot` (`trade_date`, `model`, `prompt_version`, `data_snapshot_hash`),
  KEY `idx_limit_up_analysis_trade_status` (`trade_date`, `status`),
  KEY `idx_limit_up_analysis_generated` (`generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打板 LLM 分析报告缓存表';

CREATE TABLE IF NOT EXISTS `limit_up_push_recipient` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL COMMENT '接收报告的系统用户 ID',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否接收常规数据就绪推送和手动推送',
  `weekend_replay_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否接收周六和周日晚间缓存报告复推',
  `created_by_user_id` INT DEFAULT NULL COMMENT '首次配置管理员用户 ID',
  `updated_by_user_id` INT DEFAULT NULL COMMENT '最近修改管理员用户 ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_limit_up_push_recipient_user` (`user_id`),
  KEY `idx_limit_up_push_recipient_enabled` (`enabled`),
  CONSTRAINT `fk_limit_up_push_recipient_user`
    FOREIGN KEY (`user_id`) REFERENCES `app_user` (`id`),
  CONSTRAINT `fk_limit_up_push_recipient_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `app_user` (`id`),
  CONSTRAINT `fk_limit_up_push_recipient_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `app_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打板报告 PushPlus 接收人配置表';

CREATE TABLE IF NOT EXISTS `limit_up_push_delivery` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `analysis_id` INT NOT NULL COMMENT '打板报告缓存 ID',
  `user_id` INT NOT NULL COMMENT '接收系统用户 ID',
  `scheduled_kind` VARCHAR(32) NOT NULL COMMENT '计划类型，DATA_READY、SATURDAY_REPLAY、SUNDAY_REPLAY、MANUAL',
  `scheduled_at` DATETIME NOT NULL COMMENT '业务计划时间，用于定时任务重跑幂等',
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '推送状态，PENDING、SENT、FAILED、SKIPPED',
  `pushplus_message_log_id` INT DEFAULT NULL COMMENT '对应 PushPlus 消息流水 ID',
  `error_message` TEXT DEFAULT NULL COMMENT '失败或跳过原因',
  `sent_at` DATETIME DEFAULT NULL COMMENT '发送成功时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_limit_up_push_delivery_once` (`analysis_id`, `scheduled_kind`, `scheduled_at`, `user_id`),
  KEY `idx_limit_up_push_delivery_status` (`status`, `scheduled_at`),
  KEY `idx_limit_up_push_delivery_user` (`user_id`, `scheduled_at`),
  CONSTRAINT `fk_limit_up_push_delivery_analysis`
    FOREIGN KEY (`analysis_id`) REFERENCES `limit_up_analysis_cache` (`id`),
  CONSTRAINT `fk_limit_up_push_delivery_user`
    FOREIGN KEY (`user_id`) REFERENCES `app_user` (`id`),
  CONSTRAINT `fk_limit_up_push_delivery_log`
    FOREIGN KEY (`pushplus_message_log_id`) REFERENCES `pushplus_message_log` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打板报告业务推送计划与结果表';

CREATE TABLE IF NOT EXISTS `limit_up_report_share` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `analysis_id` INT NOT NULL COMMENT '被分享的打板报告缓存 ID',
  `share_token` VARCHAR(64) NOT NULL COMMENT '临时公开查看 token，不包含用户或报告明文信息',
  `expires_at` DATETIME DEFAULT NULL COMMENT '分享链接过期时间，NULL 表示永久有效',
  `created_by_user_id` INT DEFAULT NULL COMMENT '创建分享的管理员用户 ID',
  `revoked_at` DATETIME DEFAULT NULL COMMENT '撤销时间，非空表示链接已失效',
  `last_viewed_at` DATETIME DEFAULT NULL COMMENT '最近一次公开查看时间',
  `view_count` INT NOT NULL DEFAULT 0 COMMENT '公开查看次数',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_limit_up_report_share_token` (`share_token`),
  KEY `idx_limit_up_report_share_analysis` (`analysis_id`, `created_at`),
  KEY `idx_limit_up_report_share_expires` (`expires_at`),
  CONSTRAINT `fk_limit_up_report_share_analysis`
    FOREIGN KEY (`analysis_id`) REFERENCES `limit_up_analysis_cache` (`id`),
  CONSTRAINT `fk_limit_up_report_share_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `app_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='打板报告临时分享链接表';

CREATE TABLE IF NOT EXISTS `xueqiu_publish_credential` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `enabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用雪球发布登录态',
  `cookie_text` LONGTEXT NOT NULL COMMENT '雪球创作者后台 Cookie，仅后端使用，不向前端明文返回',
  `user_agent` VARCHAR(512) NOT NULL COMMENT '调用雪球接口时使用的浏览器 User-Agent',
  `mp_base_url` VARCHAR(128) NOT NULL DEFAULT 'https://mp.xueqiu.com' COMMENT '雪球创作者后台基础地址',
  `referer_url` VARCHAR(255) NOT NULL DEFAULT 'https://mp.xueqiu.com/write/' COMMENT '雪球写作页 Referer',
  `expires_at` DATETIME DEFAULT NULL COMMENT '登录态人工标记过期时间，NULL 表示未设置',
  `last_verified_at` DATETIME DEFAULT NULL COMMENT '最近一次验证登录态可用时间',
  `last_error` TEXT DEFAULT NULL COMMENT '最近一次验证或发布失败摘要',
  `updated_by_user_id` INT DEFAULT NULL COMMENT '最近更新登录态的管理员用户 ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_xueqiu_publish_credential_enabled` (`enabled`),
  CONSTRAINT `fk_xueqiu_publish_credential_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `app_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='雪球发布登录态配置表';

CREATE TABLE IF NOT EXISTS `xueqiu_publish_setting` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `scheduler_enabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用工作日自动保存草稿或发布',
  `auto_publish` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '定时任务是否正式发布，0 表示仅保存草稿',
  `poll_hours` VARCHAR(32) NOT NULL DEFAULT '8' COMMENT '东八区定时小时 cron 字段，默认 8 点',
  `poll_minutes` VARCHAR(64) NOT NULL DEFAULT '30' COMMENT '东八区定时分钟 cron 字段，默认 30 分',
  `default_cover_pic` VARCHAR(512) DEFAULT NULL COMMENT '定时任务和页面默认使用的雪球封面图 URL',
  `updated_by_user_id` INT DEFAULT NULL COMMENT '最近更新配置的管理员用户 ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_xueqiu_publish_setting_updated_by`
    FOREIGN KEY (`updated_by_user_id`) REFERENCES `app_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='雪球发布定时配置表';

CREATE TABLE IF NOT EXISTS `xueqiu_publish_record` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `analysis_id` INT NOT NULL COMMENT '关联的打板报告缓存 ID',
  `publish_mode` VARCHAR(16) NOT NULL COMMENT '发布模式，DRAFT 草稿或 PUBLISH 正式发布',
  `status` VARCHAR(16) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING、DRAFTED、PUBLISHED、FAILED',
  `title` VARCHAR(180) NOT NULL COMMENT '发布到雪球的长文标题',
  `content_html` LONGTEXT NOT NULL COMMENT '发布到雪球的长文 HTML 正文',
  `cover_pic` VARCHAR(512) DEFAULT NULL COMMENT '雪球封面图 URL，可为空',
  `draft_id` VARCHAR(128) DEFAULT NULL COMMENT '雪球草稿 ID',
  `status_id` VARCHAR(128) DEFAULT NULL COMMENT '雪球正式发布后的状态或文章 ID',
  `article_url` VARCHAR(512) DEFAULT NULL COMMENT '雪球文章公开 URL',
  `request_payload_json` LONGTEXT DEFAULT NULL COMMENT '请求摘要 JSON，敏感 token 做脱敏处理',
  `response_json` LONGTEXT DEFAULT NULL COMMENT '雪球接口响应 JSON',
  `error_message` TEXT DEFAULT NULL COMMENT '失败原因摘要',
  `published_at` DATETIME DEFAULT NULL COMMENT '正式发布完成时间',
  `created_by_user_id` INT DEFAULT NULL COMMENT '触发草稿或发布的管理员用户 ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_xueqiu_publish_record_mode_latest` (`analysis_id`, `publish_mode`, `created_at`),
  KEY `idx_xueqiu_publish_record_status` (`status`, `created_at`),
  KEY `idx_xueqiu_publish_record_analysis` (`analysis_id`),
  CONSTRAINT `fk_xueqiu_publish_record_analysis`
    FOREIGN KEY (`analysis_id`) REFERENCES `limit_up_analysis_cache` (`id`),
  CONSTRAINT `fk_xueqiu_publish_record_created_by`
    FOREIGN KEY (`created_by_user_id`) REFERENCES `app_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='雪球长文草稿与发布流水表';

CREATE TABLE IF NOT EXISTS `stock_selection_factor_snapshot` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `factor_date` DATE NOT NULL COMMENT '因子快照日期',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `symbol` VARCHAR(16) DEFAULT NULL COMMENT '股票交易代码',
  `name` VARCHAR(64) NOT NULL COMMENT '股票简称',
  `industry` VARCHAR(128) DEFAULT NULL COMMENT '所属行业',
  `area` VARCHAR(64) DEFAULT NULL COMMENT '所属地域',
  `market` VARCHAR(64) DEFAULT NULL COMMENT '市场板块',
  `selection_tags` VARCHAR(128) NOT NULL COMMENT '筛选标签，逗号分隔',
  `selection_score` DECIMAL(20,8) DEFAULT NULL COMMENT '综合筛选分',
  `selection_reason` TEXT DEFAULT NULL COMMENT '入选原因说明',
  `is_hs300` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否沪深300成分',
  `is_sse50` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否上证50成分',
  `is_csi300_value` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否沪深300价值指数成分',
  `is_csi_dividend` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否中证红利指数成分',
  `is_sse_dividend` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否上证红利指数成分',
  `is_sz_dividend` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否深证红利指数成分',
  `close` DECIMAL(20,6) DEFAULT NULL COMMENT '最新收盘价',
  `pct_chg` DECIMAL(12,6) DEFAULT NULL COMMENT '最新涨跌幅',
  `turnover_rate` DECIMAL(20,8) DEFAULT NULL COMMENT '换手率',
  `pe_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT '滚动市盈率',
  `pb` DECIMAL(20,8) DEFAULT NULL COMMENT '市净率',
  `ps_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT '滚动市销率',
  `dividend_yield_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT '滚动股息率',
  `total_mv` DECIMAL(24,6) DEFAULT NULL COMMENT '总市值，单位万元',
  `circ_mv` DECIMAL(24,6) DEFAULT NULL COMMENT '流通市值，单位万元',
  `roe` DECIMAL(20,8) DEFAULT NULL COMMENT '最近报告期 ROE',
  `grossprofit_margin` DECIMAL(20,8) DEFAULT NULL COMMENT '毛利率',
  `netprofit_margin` DECIMAL(20,8) DEFAULT NULL COMMENT '净利率',
  `debt_to_assets` DECIMAL(20,8) DEFAULT NULL COMMENT '资产负债率',
  `revenue_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '营业收入同比',
  `latest_report_period` DATE DEFAULT NULL COMMENT '最近财报报告期',
  `return_20d` DECIMAL(20,8) DEFAULT NULL COMMENT '近 20 个交易日涨跌幅',
  `return_60d` DECIMAL(20,8) DEFAULT NULL COMMENT '近 60 个交易日涨跌幅',
  `return_120d` DECIMAL(20,8) DEFAULT NULL COMMENT '近 120 个交易日涨跌幅',
  `latest_dividend_year` VARCHAR(16) DEFAULT NULL COMMENT '最近分红年度',
  `latest_cash_div_tax` DECIMAL(20,8) DEFAULT NULL COMMENT '最近税后现金分红',
  `latest_dividend_proc` VARCHAR(64) DEFAULT NULL COMMENT '最近分红进度',
  `forecast_type` VARCHAR(64) DEFAULT NULL COMMENT '最近业绩预告类型',
  `forecast_summary` TEXT DEFAULT NULL COMMENT '最近业绩预告摘要',
  `data_source` VARCHAR(32) NOT NULL DEFAULT 'TUSHARE' COMMENT '数据来源',
  `source_trade_date` DATE DEFAULT NULL COMMENT '行情来源交易日',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_stock_selection_factor` (`factor_date`, `ts_code`),
  KEY `idx_selection_factor_date_score` (`factor_date`, `selection_score`),
  KEY `idx_selection_factor_tags` (`selection_tags`),
  KEY `idx_selection_factor_industry` (`industry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股选股因子快照宽表';

CREATE TABLE IF NOT EXISTS `a_income_statement` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE DEFAULT NULL COMMENT '公告日期',
  `f_ann_date` DATE DEFAULT NULL COMMENT '实际公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `report_type` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '报告类型',
  `comp_type` VARCHAR(16) DEFAULT NULL COMMENT '公司类型',
  `end_type` VARCHAR(16) DEFAULT NULL COMMENT '报告期类型',
  `basic_eps` DECIMAL(20,8) DEFAULT NULL COMMENT '基本每股收益',
  `diluted_eps` DECIMAL(20,8) DEFAULT NULL COMMENT '稀释每股收益',
  `total_revenue` DECIMAL(24,6) DEFAULT NULL COMMENT '营业总收入',
  `revenue` DECIMAL(24,6) DEFAULT NULL COMMENT '营业收入',
  `total_cogs` DECIMAL(24,6) DEFAULT NULL COMMENT '营业总成本',
  `oper_cost` DECIMAL(24,6) DEFAULT NULL COMMENT '营业成本',
  `biz_tax_surchg` DECIMAL(24,6) DEFAULT NULL COMMENT '营业税金及附加',
  `sell_exp` DECIMAL(24,6) DEFAULT NULL COMMENT '销售费用',
  `admin_exp` DECIMAL(24,6) DEFAULT NULL COMMENT '管理费用',
  `fin_exp` DECIMAL(24,6) DEFAULT NULL COMMENT '财务费用',
  `rd_exp` DECIMAL(24,6) DEFAULT NULL COMMENT '研发费用',
  `assets_impair_loss` DECIMAL(24,6) DEFAULT NULL COMMENT '资产减值损失',
  `credit_impa_loss` DECIMAL(24,6) DEFAULT NULL COMMENT '信用减值损失',
  `oth_income` DECIMAL(24,6) DEFAULT NULL COMMENT '其他收益',
  `asset_disp_income` DECIMAL(24,6) DEFAULT NULL COMMENT '资产处置收益',
  `operate_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '营业利润',
  `non_oper_income` DECIMAL(24,6) DEFAULT NULL COMMENT '营业外收入',
  `non_oper_exp` DECIMAL(24,6) DEFAULT NULL COMMENT '营业外支出',
  `total_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '利润总额',
  `income_tax` DECIMAL(24,6) DEFAULT NULL COMMENT '所得税',
  `n_income` DECIMAL(24,6) DEFAULT NULL COMMENT '净利润',
  `n_income_attr_p` DECIMAL(24,6) DEFAULT NULL COMMENT '归母净利润',
  `minority_gain` DECIMAL(24,6) DEFAULT NULL COMMENT '少数股东损益',
  `invest_income` DECIMAL(24,6) DEFAULT NULL COMMENT '投资收益',
  `fv_value_chg_gain` DECIMAL(24,6) DEFAULT NULL COMMENT '公允价值变动收益',
  `ebit` DECIMAL(24,6) DEFAULT NULL COMMENT '息税前利润',
  `ebitda` DECIMAL(24,6) DEFAULT NULL COMMENT '息税折旧摊销前利润',
  `update_flag` VARCHAR(8) NOT NULL DEFAULT '' COMMENT '更新标识',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_income_statement` (`ts_code`, `end_date`, `report_type`, `update_flag`),
  KEY `idx_a_income_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股利润表核心字段表';

CREATE TABLE IF NOT EXISTS `a_balance_sheet` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE DEFAULT NULL COMMENT '公告日期',
  `f_ann_date` DATE DEFAULT NULL COMMENT '实际公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `report_type` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '报告类型',
  `comp_type` VARCHAR(16) DEFAULT NULL COMMENT '公司类型',
  `total_assets` DECIMAL(24,6) DEFAULT NULL COMMENT '资产总计',
  `total_liab` DECIMAL(24,6) DEFAULT NULL COMMENT '负债合计',
  `total_hldr_eqy_inc_min_int` DECIMAL(24,6) DEFAULT NULL COMMENT '股东权益合计含少数股东',
  `total_hldr_eqy_exc_min_int` DECIMAL(24,6) DEFAULT NULL COMMENT '归母股东权益',
  `money_cap` DECIMAL(24,6) DEFAULT NULL COMMENT '货币资金',
  `trad_asset` DECIMAL(24,6) DEFAULT NULL COMMENT '交易性金融资产',
  `lt_eqt_invest` DECIMAL(24,6) DEFAULT NULL COMMENT '长期股权投资',
  `invest_real_estate` DECIMAL(24,6) DEFAULT NULL COMMENT '投资性房地产',
  `notes_receiv` DECIMAL(24,6) DEFAULT NULL COMMENT '应收票据',
  `accounts_receiv` DECIMAL(24,6) DEFAULT NULL COMMENT '应收账款',
  `oth_receiv` DECIMAL(24,6) DEFAULT NULL COMMENT '其他应收款',
  `inventories` DECIMAL(24,6) DEFAULT NULL COMMENT '存货',
  `fix_assets` DECIMAL(24,6) DEFAULT NULL COMMENT '固定资产',
  `cip` DECIMAL(24,6) DEFAULT NULL COMMENT '在建工程',
  `intan_assets` DECIMAL(24,6) DEFAULT NULL COMMENT '无形资产',
  `goodwill` DECIMAL(24,6) DEFAULT NULL COMMENT '商誉',
  `total_cur_assets` DECIMAL(24,6) DEFAULT NULL COMMENT '流动资产合计',
  `total_nca` DECIMAL(24,6) DEFAULT NULL COMMENT '非流动资产合计',
  `st_borr` DECIMAL(24,6) DEFAULT NULL COMMENT '短期借款',
  `notes_payable` DECIMAL(24,6) DEFAULT NULL COMMENT '应付票据',
  `acct_payable` DECIMAL(24,6) DEFAULT NULL COMMENT '应付账款',
  `contract_liab` DECIMAL(24,6) DEFAULT NULL COMMENT '合同负债',
  `lt_borr` DECIMAL(24,6) DEFAULT NULL COMMENT '长期借款',
  `bond_payable` DECIMAL(24,6) DEFAULT NULL COMMENT '应付债券',
  `total_cur_liab` DECIMAL(24,6) DEFAULT NULL COMMENT '流动负债合计',
  `total_ncl` DECIMAL(24,6) DEFAULT NULL COMMENT '非流动负债合计',
  `cap_rese` DECIMAL(24,6) DEFAULT NULL COMMENT '资本公积',
  `surplus_rese` DECIMAL(24,6) DEFAULT NULL COMMENT '盈余公积',
  `undistr_porfit` DECIMAL(24,6) DEFAULT NULL COMMENT '未分配利润',
  `update_flag` VARCHAR(8) NOT NULL DEFAULT '' COMMENT '更新标识',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_balance_sheet` (`ts_code`, `end_date`, `report_type`, `update_flag`),
  KEY `idx_a_balance_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股资产负债表核心字段表';

CREATE TABLE IF NOT EXISTS `a_cashflow_statement` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE DEFAULT NULL COMMENT '公告日期',
  `f_ann_date` DATE DEFAULT NULL COMMENT '实际公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `report_type` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '报告类型',
  `comp_type` VARCHAR(16) DEFAULT NULL COMMENT '公司类型',
  `net_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '净利润',
  `finan_exp` DECIMAL(24,6) DEFAULT NULL COMMENT '财务费用',
  `c_fr_sale_sg` DECIMAL(24,6) DEFAULT NULL COMMENT '销售商品提供劳务收到的现金',
  `c_paid_goods_s` DECIMAL(24,6) DEFAULT NULL COMMENT '购买商品接受劳务支付的现金',
  `c_paid_to_for_empl` DECIMAL(24,6) DEFAULT NULL COMMENT '支付给职工以及为职工支付的现金',
  `c_paid_for_taxes` DECIMAL(24,6) DEFAULT NULL COMMENT '支付的各项税费',
  `n_cashflow_act` DECIMAL(24,6) DEFAULT NULL COMMENT '经营活动现金流净额',
  `c_recp_return_invest` DECIMAL(24,6) DEFAULT NULL COMMENT '取得投资收益收到的现金',
  `n_recp_disp_fiolta` DECIMAL(24,6) DEFAULT NULL COMMENT '处置固定资产等收回现金净额',
  `c_pay_acq_const_fiolta` DECIMAL(24,6) DEFAULT NULL COMMENT '购建固定资产等支付的现金',
  `n_cashflow_inv_act` DECIMAL(24,6) DEFAULT NULL COMMENT '投资活动现金流净额',
  `c_recp_borrow` DECIMAL(24,6) DEFAULT NULL COMMENT '取得借款收到的现金',
  `c_prepay_amt_borr` DECIMAL(24,6) DEFAULT NULL COMMENT '偿还债务支付的现金',
  `c_pay_dist_dpcp_int_exp` DECIMAL(24,6) DEFAULT NULL COMMENT '分配股利利润或偿付利息支付的现金',
  `n_cash_flows_fnc_act` DECIMAL(24,6) DEFAULT NULL COMMENT '筹资活动现金流净额',
  `n_incr_cash_cash_equ` DECIMAL(24,6) DEFAULT NULL COMMENT '现金及等价物净增加额',
  `c_cash_equ_end_period` DECIMAL(24,6) DEFAULT NULL COMMENT '期末现金及等价物余额',
  `update_flag` VARCHAR(8) NOT NULL DEFAULT '' COMMENT '更新标识',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_cashflow_statement` (`ts_code`, `end_date`, `report_type`, `update_flag`),
  KEY `idx_a_cashflow_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股现金流量表核心字段表';

CREATE TABLE IF NOT EXISTS `a_financial_indicator` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE DEFAULT NULL COMMENT '公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `eps` DECIMAL(20,8) DEFAULT NULL COMMENT '每股收益',
  `dt_eps` DECIMAL(20,8) DEFAULT NULL COMMENT '稀释每股收益',
  `roe` DECIMAL(20,8) DEFAULT NULL COMMENT '净资产收益率',
  `roe_waa` DECIMAL(20,8) DEFAULT NULL COMMENT '加权平均净资产收益率',
  `roe_dt` DECIMAL(20,8) DEFAULT NULL COMMENT '扣非摊薄 ROE',
  `roa` DECIMAL(20,8) DEFAULT NULL COMMENT '总资产报酬率',
  `grossprofit_margin` DECIMAL(20,8) DEFAULT NULL COMMENT '毛利率',
  `netprofit_margin` DECIMAL(20,8) DEFAULT NULL COMMENT '净利率',
  `sales_gpr` DECIMAL(20,8) DEFAULT NULL COMMENT '销售毛利率',
  `profit_to_gr` DECIMAL(20,8) DEFAULT NULL COMMENT '净利润与营业总收入比',
  `debt_to_assets` DECIMAL(20,8) DEFAULT NULL COMMENT '资产负债率',
  `current_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '流动比率',
  `quick_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '速动比率',
  `assets_to_eqt` DECIMAL(20,8) DEFAULT NULL COMMENT '权益乘数',
  `or_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '营业收入同比',
  `q_sales_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '单季度营业收入同比',
  `netprofit_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '净利润同比',
  `q_netprofit_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '单季度净利润同比',
  `ocf_to_revenue` DECIMAL(20,8) DEFAULT NULL COMMENT '经营现金流与营收比',
  `ocfps` DECIMAL(20,8) DEFAULT NULL COMMENT '每股经营现金流',
  `roe_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT 'ROE 同比',
  `bps` DECIMAL(20,8) DEFAULT NULL COMMENT '每股净资产',
  `profit_dedt` DECIMAL(24,6) DEFAULT NULL COMMENT '扣非净利润',
  `update_flag` VARCHAR(8) DEFAULT NULL COMMENT '更新标识',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_financial_indicator` (`ts_code`, `end_date`),
  KEY `idx_a_fin_indicator_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股财务指标核心字段表';


CREATE TABLE IF NOT EXISTS `hk_financial_indicator` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT '港股 Tushare 代码',
  `name` VARCHAR(128) DEFAULT NULL COMMENT '港股名称',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `report_type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '报告类型',
  `std_report_date` DATE DEFAULT NULL COMMENT '标准报告期',
  `start_date` DATE DEFAULT NULL COMMENT '报告起始日',
  `fiscal_year` INT DEFAULT NULL COMMENT '财政年度月份',
  `currency` VARCHAR(16) DEFAULT NULL COMMENT '币种',
  `org_type` VARCHAR(64) DEFAULT NULL COMMENT '公司类型',
  `per_netcash_operate` DECIMAL(20,8) DEFAULT NULL COMMENT '每股经营现金流',
  `per_oi` DECIMAL(20,8) DEFAULT NULL COMMENT '每股营业收入',
  `bps` DECIMAL(20,8) DEFAULT NULL COMMENT '每股净资产',
  `basic_eps` DECIMAL(20,8) DEFAULT NULL COMMENT '基本每股收益',
  `diluted_eps` DECIMAL(20,8) DEFAULT NULL COMMENT '摊薄每股收益',
  `operate_income` DECIMAL(24,6) DEFAULT NULL COMMENT '营业收入',
  `operate_income_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '营业收入同比',
  `gross_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '毛利',
  `gross_profit_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '毛利同比',
  `holder_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '股东应占利润',
  `holder_profit_yoy` DECIMAL(20,8) DEFAULT NULL COMMENT '股东应占利润同比',
  `gross_profit_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '毛利率',
  `eps_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT 'TTM 每股收益',
  `operate_income_qoq` DECIMAL(20,8) DEFAULT NULL COMMENT '营业收入环比',
  `net_profit_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '净利率',
  `roe_avg` DECIMAL(20,8) DEFAULT NULL COMMENT '平均 ROE',
  `gross_profit_qoq` DECIMAL(20,8) DEFAULT NULL COMMENT '毛利环比',
  `roa` DECIMAL(20,8) DEFAULT NULL COMMENT 'ROA',
  `holder_profit_qoq` DECIMAL(20,8) DEFAULT NULL COMMENT '股东应占利润环比',
  `roe_yearly` DECIMAL(20,8) DEFAULT NULL COMMENT '年度 ROE',
  `roic_yearly` DECIMAL(20,8) DEFAULT NULL COMMENT '年度 ROIC',
  `total_assets` DECIMAL(24,6) DEFAULT NULL COMMENT '资产总计',
  `total_liabilities` DECIMAL(24,6) DEFAULT NULL COMMENT '负债合计',
  `tax_ebt` DECIMAL(20,8) DEFAULT NULL COMMENT '税前利润税率',
  `ocf_sales` DECIMAL(20,8) DEFAULT NULL COMMENT '经营现金流与收入比',
  `total_parent_equity` DECIMAL(24,6) DEFAULT NULL COMMENT '母公司股东权益',
  `debt_asset_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '资产负债率',
  `operate_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '营业利润',
  `pretax_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '税前利润',
  `netcash_operate` DECIMAL(24,6) DEFAULT NULL COMMENT '经营现金流净额',
  `netcash_invest` DECIMAL(24,6) DEFAULT NULL COMMENT '投资现金流净额',
  `netcash_finance` DECIMAL(24,6) DEFAULT NULL COMMENT '筹资现金流净额',
  `end_cash` DECIMAL(24,6) DEFAULT NULL COMMENT '期末现金',
  `divi_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '派息比例',
  `dividend_rate` DECIMAL(20,8) DEFAULT NULL COMMENT '股息率',
  `current_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '流动比率',
  `currentdebt_debt` DECIMAL(20,8) DEFAULT NULL COMMENT '流动负债占负债比',
  `total_market_cap` DECIMAL(24,6) DEFAULT NULL COMMENT '总市值',
  `hksk_market_cap` DECIMAL(24,6) DEFAULT NULL COMMENT '港股市值',
  `pe_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT 'PE TTM',
  `pb_ttm` DECIMAL(20,8) DEFAULT NULL COMMENT 'PB TTM',
  `dps_hkd` DECIMAL(20,8) DEFAULT NULL COMMENT '每股股息 HKD',
  `dps_hkd_ly` DECIMAL(20,8) DEFAULT NULL COMMENT '上年每股股息 HKD',
  `equity_multiplier` DECIMAL(20,8) DEFAULT NULL COMMENT '权益乘数',
  `equity_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '权益比率',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hk_financial_indicator` (`ts_code`, `end_date`, `report_type`),
  KEY `idx_hk_fin_indicator_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='港股财务指标摘要表';

CREATE TABLE IF NOT EXISTS `hk_financial_statement_item` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT '港股 Tushare 代码',
  `name` VARCHAR(128) DEFAULT NULL COMMENT '港股名称',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `statement_type` VARCHAR(16) NOT NULL COMMENT '报表类型：INCOME/BALANCE/CASHFLOW',
  `ind_name` VARCHAR(128) NOT NULL COMMENT '指标名称',
  `ind_value` DECIMAL(24,6) DEFAULT NULL COMMENT '指标值',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hk_fin_statement_item` (`ts_code`, `end_date`, `statement_type`, `ind_name`),
  KEY `idx_hk_fin_statement_code_period` (`ts_code`, `end_date`),
  KEY `idx_hk_fin_statement_type` (`statement_type`, `ind_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='港股三大财务报表项目明细表';

CREATE TABLE IF NOT EXISTS `a_dividend` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `end_date` DATE NOT NULL COMMENT '分红年度或报告期',
  `ann_date` DATE NOT NULL COMMENT '公告日期',
  `div_proc` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '分红进度',
  `stk_div` DECIMAL(20,8) DEFAULT NULL COMMENT '送转股比例',
  `cash_div` DECIMAL(20,8) DEFAULT NULL COMMENT '每股分红税前',
  `cash_div_tax` DECIMAL(20,8) DEFAULT NULL COMMENT '每股分红税后',
  `record_date` DATE DEFAULT NULL COMMENT '股权登记日',
  `ex_date` DATE DEFAULT NULL COMMENT '除权除息日',
  `pay_date` DATE DEFAULT NULL COMMENT '派息日',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_dividend` (`ts_code`, `end_date`, `ann_date`, `div_proc`),
  KEY `idx_a_dividend_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股分红送股表';

CREATE TABLE IF NOT EXISTS `a_forecast` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE NOT NULL COMMENT '公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '预告类型',
  `p_change_min` DECIMAL(20,8) DEFAULT NULL COMMENT '业绩变动下限百分比',
  `p_change_max` DECIMAL(20,8) DEFAULT NULL COMMENT '业绩变动上限百分比',
  `net_profit_min` DECIMAL(24,6) DEFAULT NULL COMMENT '预告净利润下限',
  `net_profit_max` DECIMAL(24,6) DEFAULT NULL COMMENT '预告净利润上限',
  `last_parent_net` DECIMAL(24,6) DEFAULT NULL COMMENT '上年同期归母净利润',
  `first_ann_date` DATE DEFAULT NULL COMMENT '首次公告日',
  `summary` TEXT DEFAULT NULL COMMENT '预告摘要',
  `change_reason` TEXT DEFAULT NULL COMMENT '业绩变动原因',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_forecast` (`ts_code`, `ann_date`, `end_date`, `type`),
  KEY `idx_a_forecast_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股业绩预告表';

CREATE TABLE IF NOT EXISTS `a_main_business_composition` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `business_type` VARCHAR(8) NOT NULL DEFAULT '' COMMENT '主营构成口径，PRODUCT 产品、REGION 地区',
  `bz_item` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '主营业务项目',
  `bz_sales` DECIMAL(24,6) DEFAULT NULL COMMENT '主营业务收入',
  `bz_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '主营业务利润',
  `bz_cost` DECIMAL(24,6) DEFAULT NULL COMMENT '主营业务成本',
  `curr_type` VARCHAR(16) DEFAULT NULL COMMENT '货币代码',
  `update_flag` VARCHAR(8) DEFAULT NULL COMMENT '更新标识',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_main_business_composition` (`ts_code`, `end_date`, `business_type`, `bz_item`),
  KEY `idx_a_main_business_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股主营业务构成表';

CREATE TABLE IF NOT EXISTS `a_financial_audit` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE NOT NULL COMMENT '公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `audit_result` VARCHAR(128) DEFAULT NULL COMMENT '审计结果',
  `audit_fees` DECIMAL(24,6) DEFAULT NULL COMMENT '审计费用',
  `audit_agency` VARCHAR(255) DEFAULT NULL COMMENT '会计师事务所',
  `audit_sign` VARCHAR(255) DEFAULT NULL COMMENT '签字会计师',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_financial_audit` (`ts_code`, `ann_date`, `end_date`),
  KEY `idx_a_financial_audit_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股财务审计意见表';

CREATE TABLE IF NOT EXISTS `a_express` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE NOT NULL COMMENT '公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `revenue` DECIMAL(24,6) DEFAULT NULL COMMENT '营业收入',
  `operate_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '营业利润',
  `total_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '利润总额',
  `n_income` DECIMAL(24,6) DEFAULT NULL COMMENT '净利润',
  `total_assets` DECIMAL(24,6) DEFAULT NULL COMMENT '总资产',
  `total_hldr_eqy_exc_min_int` DECIMAL(24,6) DEFAULT NULL COMMENT '归母股东权益',
  `diluted_eps` DECIMAL(20,8) DEFAULT NULL COMMENT '摊薄每股收益',
  `diluted_roe` DECIMAL(20,8) DEFAULT NULL COMMENT '摊薄净资产收益率',
  `yoy_net_profit` DECIMAL(24,6) DEFAULT NULL COMMENT '去年同期净利润',
  `bps` DECIMAL(20,8) DEFAULT NULL COMMENT '每股净资产',
  `yoy_sales` DECIMAL(20,8) DEFAULT NULL COMMENT '营业收入同比',
  `yoy_op` DECIMAL(20,8) DEFAULT NULL COMMENT '营业利润同比',
  `yoy_tp` DECIMAL(20,8) DEFAULT NULL COMMENT '利润总额同比',
  `yoy_dedu_np` DECIMAL(20,8) DEFAULT NULL COMMENT '归母净利润同比',
  `yoy_eps` DECIMAL(20,8) DEFAULT NULL COMMENT '每股收益同比',
  `yoy_roe` DECIMAL(20,8) DEFAULT NULL COMMENT '加权 ROE 同比',
  `growth_assets` DECIMAL(20,8) DEFAULT NULL COMMENT '总资产较年初增长率',
  `yoy_equity` DECIMAL(20,8) DEFAULT NULL COMMENT '归母权益较年初增长率',
  `growth_bps` DECIMAL(20,8) DEFAULT NULL COMMENT '每股净资产较年初增长率',
  `perf_summary` TEXT DEFAULT NULL COMMENT '业绩简要说明',
  `is_audit` INT DEFAULT NULL COMMENT '是否审计',
  `remark` TEXT DEFAULT NULL COMMENT '备注',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_express` (`ts_code`, `ann_date`, `end_date`),
  KEY `idx_a_express_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股业绩快报表';

CREATE TABLE IF NOT EXISTS `a_top10_holder` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE DEFAULT NULL COMMENT '公告日期',
  `end_date` DATE NOT NULL COMMENT '报告期',
  `holder_scope` VARCHAR(16) NOT NULL DEFAULT '' COMMENT '股东范围，TOTAL 前十大股东、FLOAT 前十大流通股东',
  `holder_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '股东名称',
  `hold_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '持股数量',
  `hold_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '持股比例',
  `hold_float_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '流通股持股比例',
  `hold_change` DECIMAL(24,6) DEFAULT NULL COMMENT '持股变动',
  `holder_type` VARCHAR(128) DEFAULT NULL COMMENT '股东类型',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_top10_holder` (`ts_code`, `end_date`, `holder_scope`, `holder_name`),
  KEY `idx_a_top10_holder_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股前十大股东和前十大流通股东表';

CREATE TABLE IF NOT EXISTS `a_holder_number` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `ann_date` DATE NOT NULL COMMENT '公告日期',
  `end_date` DATE NOT NULL COMMENT '截止日期',
  `holder_num` INT DEFAULT NULL COMMENT '股东户数',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_holder_number` (`ts_code`, `end_date`, `ann_date`),
  KEY `idx_a_holder_number_code_period` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股股东户数表';

CREATE TABLE IF NOT EXISTS `a_pledge_stat` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `end_date` DATE NOT NULL COMMENT '截止日期',
  `pledge_count` INT DEFAULT NULL COMMENT '质押次数',
  `unrest_pledge` DECIMAL(24,6) DEFAULT NULL COMMENT '无限售股质押数量',
  `rest_pledge` DECIMAL(24,6) DEFAULT NULL COMMENT '限售股质押数量',
  `total_share` DECIMAL(24,6) DEFAULT NULL COMMENT '总股本',
  `pledge_ratio` DECIMAL(20,8) DEFAULT NULL COMMENT '质押比例',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_pledge_stat` (`ts_code`, `end_date`),
  KEY `idx_a_pledge_stat_code_date` (`ts_code`, `end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股股权质押统计表';

CREATE TABLE IF NOT EXISTS `a_moneyflow` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `ts_code` VARCHAR(16) NOT NULL COMMENT 'A 股 Tushare 代码',
  `trade_date` DATE NOT NULL COMMENT '交易日期',
  `buy_sm_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '小单买入量',
  `buy_sm_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '小单买入金额',
  `sell_sm_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '小单卖出量',
  `sell_sm_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '小单卖出金额',
  `buy_md_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '中单买入量',
  `buy_md_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '中单买入金额',
  `sell_md_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '中单卖出量',
  `sell_md_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '中单卖出金额',
  `buy_lg_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '大单买入量',
  `buy_lg_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '大单买入金额',
  `sell_lg_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '大单卖出量',
  `sell_lg_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '大单卖出金额',
  `buy_elg_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '特大单买入量',
  `buy_elg_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '特大单买入金额',
  `sell_elg_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '特大单卖出量',
  `sell_elg_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '特大单卖出金额',
  `net_mf_vol` DECIMAL(24,6) DEFAULT NULL COMMENT '净流入量',
  `net_mf_amount` DECIMAL(24,6) DEFAULT NULL COMMENT '净流入金额',
  `raw_payload_json` TEXT DEFAULT NULL COMMENT 'Tushare 原始行 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_a_moneyflow` (`ts_code`, `trade_date`),
  KEY `idx_a_moneyflow_code_date` (`ts_code`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='A 股个股资金流向表';

CREATE TABLE IF NOT EXISTS `llm_market_data_fetch_run` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `question_id` VARCHAR(64) DEFAULT NULL COMMENT 'LLM 单轮问题追踪 ID',
  `user_id` INT DEFAULT NULL COMMENT '用户 ID',
  `session_id` INT DEFAULT NULL COMMENT '会话 ID',
  `intent` VARCHAR(64) NOT NULL DEFAULT 'stock_research' COMMENT '补数意图',
  `market_scope` VARCHAR(32) NOT NULL DEFAULT 'A_STOCK_SINGLE' COMMENT '市场范围，当前仅允许单只 A 股',
  `symbols_json` TEXT DEFAULT NULL COMMENT '本轮涉及股票代码 JSON',
  `data_packages_json` TEXT DEFAULT NULL COMMENT '白名单数据包 JSON',
  `period_policy` VARCHAR(64) NOT NULL DEFAULT 'RECENT_LIMITED' COMMENT '保守取数周期策略',
  `start_date` DATE DEFAULT NULL COMMENT '本轮开始日期',
  `end_date` DATE DEFAULT NULL COMMENT '本轮结束日期',
  `status` VARCHAR(16) NOT NULL DEFAULT 'RUNNING' COMMENT '状态: RUNNING、COMPLETED、FAILED、SKIPPED',
  `cache_hit` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否完全命中缓存',
  `row_count` INT NOT NULL DEFAULT 0 COMMENT '本轮写入或命中的上下文行数',
  `error_message` VARCHAR(512) DEFAULT NULL COMMENT '失败原因摘要',
  `started_at` DATETIME DEFAULT NULL COMMENT '开始时间',
  `finished_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_llm_market_fetch_question` (`question_id`),
  KEY `idx_llm_market_fetch_status` (`status`, `started_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM 按需市场数据抓取批次表';

CREATE TABLE IF NOT EXISTS `llm_market_data_fetch_item` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `run_id` INT DEFAULT NULL COMMENT '抓取批次 ID',
  `package_name` VARCHAR(64) NOT NULL COMMENT '数据包名称',
  `api_name` VARCHAR(64) NOT NULL COMMENT 'Tushare 接口名',
  `params_json` TEXT DEFAULT NULL COMMENT '已脱敏请求参数 JSON',
  `fields_json` TEXT DEFAULT NULL COMMENT '字段白名单 JSON',
  `status` VARCHAR(16) NOT NULL DEFAULT 'RUNNING' COMMENT '状态',
  `row_count` INT NOT NULL DEFAULT 0 COMMENT '返回或写入行数',
  `elapsed_ms` INT DEFAULT NULL COMMENT '调用耗时毫秒',
  `error_message` VARCHAR(512) DEFAULT NULL COMMENT '失败原因摘要',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_llm_market_fetch_item_run` (`run_id`),
  KEY `idx_llm_market_fetch_item_api` (`api_name`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM 按需市场数据抓取明细表';

CREATE TABLE IF NOT EXISTS `sync_run` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `dataset` VARCHAR(64) NOT NULL COMMENT '同步数据集名称',
  `params_json` TEXT DEFAULT NULL COMMENT '同步参数 JSON',
  `status` VARCHAR(32) NOT NULL COMMENT '任务状态，PENDING、RUNNING、SUCCESS、FAILED',
  `started_at` DATETIME DEFAULT NULL COMMENT '任务开始时间',
  `finished_at` DATETIME DEFAULT NULL COMMENT '任务结束时间',
  `row_count` INT NOT NULL COMMENT '本次写入或处理行数',
  `error_message` TEXT DEFAULT NULL COMMENT '失败错误信息',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步任务运行记录表';

CREATE TABLE IF NOT EXISTS `sync_checkpoint` (
  `dataset` VARCHAR(64) NOT NULL COMMENT '同步数据集名称',
  `scope_key` VARCHAR(128) NOT NULL COMMENT '同步范围键，例如 default、ts_code 或通道类型',
  `last_success_date` DATE DEFAULT NULL COMMENT '最近成功同步到的日期',
  `last_run_id` INT DEFAULT NULL COMMENT '最近成功同步任务 ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`dataset`, `scope_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据同步断点表';

CREATE TABLE IF NOT EXISTS `data_quality_issue` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `issue_date` DATE DEFAULT NULL COMMENT '问题对应日期',
  `issue_type` VARCHAR(64) NOT NULL COMMENT '问题类型',
  `severity` VARCHAR(32) NOT NULL COMMENT '严重级别，例如 INFO、WARN、ERROR',
  `ref_key` VARCHAR(128) DEFAULT NULL COMMENT '关联对象键，例如股票代码或数据集',
  `message` TEXT NOT NULL COMMENT '问题说明',
  `resolved_at` DATETIME DEFAULT NULL COMMENT '解决时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据质量问题记录表';

CREATE TABLE IF NOT EXISTS `llm_chat_session` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `user_id` INT NOT NULL DEFAULT 1 COMMENT '所属用户 ID',
  `title` VARCHAR(255) NOT NULL COMMENT '会话标题',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '逻辑删除时间，非空表示会话已删除',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_llm_chat_session_deleted_at` (`deleted_at`),
  KEY `idx_llm_chat_session_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM 问答会话表';

CREATE TABLE IF NOT EXISTS `llm_chat_message` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `session_id` INT NOT NULL COMMENT '所属会话 ID',
  `role` VARCHAR(32) NOT NULL COMMENT '消息角色，user 或 assistant',
  `content` TEXT NOT NULL COMMENT '消息正文',
  `sql_text` TEXT DEFAULT NULL COMMENT 'LLM 生成并通过校验的 SQL',
  `result_preview_json` TEXT DEFAULT NULL COMMENT '查询结果预览 JSON',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_llm_chat_message_session_id` (`session_id`),
  CONSTRAINT `fk_llm_chat_message_session`
    FOREIGN KEY (`session_id`) REFERENCES `llm_chat_session` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM 问答消息表';

CREATE TABLE IF NOT EXISTS `llm_call_metric` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `question_id` VARCHAR(32) NOT NULL COMMENT '单轮问题追踪 ID，不包含问题原文',
  `conversation_title` VARCHAR(128) DEFAULT NULL COMMENT '对话标题，由用户提问清洗截取生成',
  `user_id` INT DEFAULT NULL COMMENT '所属用户 ID',
  `user_name` VARCHAR(64) DEFAULT NULL COMMENT '用户展示名称，优先展示名称否则登录名',
  `session_id` INT DEFAULT NULL COMMENT '所属会话 ID',
  `phase` VARCHAR(64) NOT NULL COMMENT '调用阶段，如 question_router、generate_sql、answer_stream',
  `phase_label` VARCHAR(64) DEFAULT NULL COMMENT '调用阶段中文名称',
  `phase_description` TEXT DEFAULT NULL COMMENT '调用阶段中文含义说明',
  `provider` VARCHAR(32) DEFAULT NULL COMMENT '调用提供方，如 Qwen、DeepSeek、Database、Internal',
  `model` VARCHAR(64) DEFAULT NULL COMMENT '模型名称',
  `success` INT NOT NULL DEFAULT 1 COMMENT '是否成功，1 成功，0 失败',
  `elapsed_ms` DOUBLE DEFAULT NULL COMMENT '阶段耗时毫秒',
  `first_chunk_ms` DOUBLE DEFAULT NULL COMMENT '流式首包耗时毫秒',
  `output_chars` INT NOT NULL DEFAULT 0 COMMENT '输出字符数',
  `chunk_count` INT NOT NULL DEFAULT 0 COMMENT '流式 chunk 数',
  `row_count` INT NOT NULL DEFAULT 0 COMMENT '关联数据行数',
  `request_payload_json` LONGTEXT DEFAULT NULL COMMENT '调用 LLM 时的请求参数 JSON，包含上下文 messages，不包含鉴权头和 API Key',
  `response_content` LONGTEXT DEFAULT NULL COMMENT '大模型返回的原始响应内容，流式回答保存拼接后的完整内容',
  `error_message` VARCHAR(512) DEFAULT NULL COMMENT '错误摘要，不包含密钥和问题全文',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_llm_call_metric_question` (`question_id`),
  KEY `idx_llm_call_metric_user_created` (`user_id`, `created_at`),
  KEY `idx_llm_call_metric_session_created` (`session_id`, `created_at`),
  KEY `idx_llm_call_metric_phase_model` (`phase`, `model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='LLM 调用耗时指标表';
